language: ruby
script: bundle exec rspec
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.1.0
  - 2.2.0
  - 2.3.0
env:
  - RAILS_VERSION=3.2.20
  - RAILS_VERSION=4.1.7
  - RAILS_VERSION=4.2.0
  - RAILS_VERSION=5.0.0
